/* LSP
 * A division of LYRtech Inc.
 *
 * VHS-ADC-DAC routines for FPGA update : definition for common constants for CCE and Client.
 * 
 */

#ifndef _VHSADAC_IP_COMMON_H_
#define _VHSADAC_IP_COMMON_H_

#define VHS_HOST_PORT				0x7756
#define VHS_FPGA_DONE_ACK			0x67
#define VHS_FPGA_UPDATE_CMD_ADC		0x51
#define VHS_FPGA_UPDATE_CMD_DAC		0x52
#define VHS_FPGA_ERROR_ACK			0x26
#define VHS_DETECT_PORT				31422

#define VHS_DETECT_STRING			"I am looking for some VHS-ADC-DAC Boards!!"

#define VHS_ADC16_ANSWER_STRING		"I am a VHS-ADC16 BOARD! "
#define VHS_ADC32_ANSWER_STRING		"I am a VHS-ADC32 BOARD! "
#define VHS_ADC48_ANSWER_STRING		"I am a VHS-ADC48 BOARD! "
#define VHS_ADC64_ANSWER_STRING		"I am a VHS-ADC64 BOARD! "
#define VHS_ADC80_ANSWER_STRING		"I am a VHS-ADC80 BOARD! "
#define VHS_ADC96_ANSWER_STRING		"I am a VHS-ADC96 BOARD! "
#define VHS_ADC112_ANSWER_STRING	"I am a VHS-ADC112 BOARD!"
#define VHS_ADC128_ANSWER_STRING	"I am a VHS-ADC128 BOARD!"
#define VHS_ADC144_ANSWER_STRING	"I am a VHS-ADC144 BOARD!"
#define VHS_ADC160_ANSWER_STRING	"I am a VHS-ADC160 BOARD!"
#define VHS_ADC176_ANSWER_STRING	"I am a VHS-ADC176 BOARD!"
#define VHS_ADC192_ANSWER_STRING	"I am a VHS-ADC192 BOARD!"
#define VHS_ADC208_ANSWER_STRING	"I am a VHS-ADC208 BOARD!"
#define VHS_ADC224_ANSWER_STRING	"I am a VHS-ADC224 BOARD!"
#define VHS_ADC240_ANSWER_STRING	"I am a VHS-ADC240 BOARD!"
#define VHS_ADC256_ANSWER_STRING	"I am a VHS-ADC256 BOARD!"
#define VHS_ADC272_ANSWER_STRING	"I am a VHS-ADC272 BOARD!"
#define VHS_ADC288_ANSWER_STRING	"I am a VHS-ADC288 BOARD!"
#define VHS_ADC304_ANSWER_STRING	"I am a VHS-ADC304 BOARD!"
#define VHS_ADC320_ANSWER_STRING	"I am a VHS-ADC320 BOARD!"
#define VHS_ADC336_ANSWER_STRING	"I am a VHS-ADC336 BOARD!"
#define VHS_ADC352_ANSWER_STRING	"I am a VHS-ADC352 BOARD!"
#define VHS_ADC368_ANSWER_STRING	"I am a VHS-ADC368 BOARD!"
#define VHS_ADC384_ANSWER_STRING	"I am a VHS-ADC384 BOARD!"
#define VHS_ADC400_ANSWER_STRING	"I am a VHS-ADC400 BOARD!"
#define VHS_ADC416_ANSWER_STRING	"I am a VHS-ADC416 BOARD!"
#define VHS_ADC432_ANSWER_STRING	"I am a VHS-ADC432 BOARD!"
#define VHS_ADC448_ANSWER_STRING	"I am a VHS-ADC448 BOARD!"
#define VHS_ADC464_ANSWER_STRING	"I am a VHS-ADC464 BOARD!"
#define VHS_ADC480_ANSWER_STRING	"I am a VHS-ADC480 BOARD!"
#define VHS_ADC496_ANSWER_STRING	"I am a VHS-ADC496 BOARD!"
#define VHS_ADC512_ANSWER_STRING	"I am a VHS-ADC512 BOARD!"


#define VHS_DAC16_ANSWER_STRING		"I am a VHS-DAC16 BOARD! "
#define VHS_DAC32_ANSWER_STRING		"I am a VHS-DAC32 BOARD! "
#define VHS_DAC48_ANSWER_STRING		"I am a VHS-DAC48 BOARD! "
#define VHS_DAC64_ANSWER_STRING		"I am a VHS-DAC64 BOARD! "
#define VHS_DAC80_ANSWER_STRING		"I am a VHS-DAC80 BOARD! "
#define VHS_DAC96_ANSWER_STRING		"I am a VHS-DAC96 BOARD! "
#define VHS_DAC112_ANSWER_STRING	"I am a VHS-DAC112 BOARD!"
#define VHS_DAC128_ANSWER_STRING	"I am a VHS-DAC128 BOARD!"
#define VHS_DAC144_ANSWER_STRING	"I am a VHS-DAC144 BOARD!"
#define VHS_DAC160_ANSWER_STRING	"I am a VHS-DAC160 BOARD!"
#define VHS_DAC176_ANSWER_STRING	"I am a VHS-DAC176 BOARD!"
#define VHS_DAC192_ANSWER_STRING	"I am a VHS-DAC192 BOARD!"
#define VHS_DAC208_ANSWER_STRING	"I am a VHS-DAC208 BOARD!"
#define VHS_DAC224_ANSWER_STRING	"I am a VHS-DAC224 BOARD!"
#define VHS_DAC240_ANSWER_STRING	"I am a VHS-DAC240 BOARD!"
#define VHS_DAC256_ANSWER_STRING	"I am a VHS-DAC256 BOARD!"
#define VHS_DAC272_ANSWER_STRING	"I am a VHS-DAC272 BOARD!"
#define VHS_DAC288_ANSWER_STRING	"I am a VHS-DAC288 BOARD!"
#define VHS_DAC304_ANSWER_STRING	"I am a VHS-DAC304 BOARD!"
#define VHS_DAC320_ANSWER_STRING	"I am a VHS-DAC320 BOARD!"
#define VHS_DAC336_ANSWER_STRING	"I am a VHS-DAC336 BOARD!"
#define VHS_DAC352_ANSWER_STRING	"I am a VHS-DAC352 BOARD!"
#define VHS_DAC368_ANSWER_STRING	"I am a VHS-DAC368 BOARD!"
#define VHS_DAC384_ANSWER_STRING	"I am a VHS-DAC384 BOARD!"
#define VHS_DAC400_ANSWER_STRING	"I am a VHS-DAC400 BOARD!"
#define VHS_DAC416_ANSWER_STRING	"I am a VHS-DAC416 BOARD!"
#define VHS_DAC432_ANSWER_STRING	"I am a VHS-DAC432 BOARD!"
#define VHS_DAC448_ANSWER_STRING	"I am a VHS-DAC448 BOARD!"
#define VHS_DAC464_ANSWER_STRING	"I am a VHS-DAC464 BOARD!"
#define VHS_DAC480_ANSWER_STRING	"I am a VHS-DAC480 BOARD!"
#define VHS_DAC496_ANSWER_STRING	"I am a VHS-DAC496 BOARD!"
#define VHS_DAC512_ANSWER_STRING	"I am a VHS-DAC512 BOARD!"

#define XC2V3000_FPGA_ANSWER_STRING		"With FPGA XC2V3000! "
#define XC2V4000_FPGA_ANSWER_STRING		"With FPGA XC2V4000! "
#define XC2V6000_FPGA_ANSWER_STRING		"With FPGA XC2V6000! "
#define XC2V8000_FPGA_ANSWER_STRING		"With FPGA XC2V8000! "
#define XC4LX40_FPGA_ANSWER_STRING		"With FPGA XC4LX40! "
#define XC4LX60_FPGA_ANSWER_STRING		"With FPGA XC4LX60! "
#define XC4LX80_FPGA_ANSWER_STRING		"With FPGA XC4LX80! "
#define XC4LX100_FPGA_ANSWER_STRING		"With FPGA XC4LX100! "
#define XC4LX160_FPGA_ANSWER_STRING		"With FPGA XC4LX160! "
#define XC4SX55_FPGA_ANSWER_STRING		"With FPGA XC4SX55! "
#define DIFFERENT_FPGA_ANSWER_STRING	"With Different FPGA!"

#define VHS_ADC_TYPE_STRING_SIZE	max(sizeof(VHS_ADC128_ANSWER_STRING),sizeof(VHS_DAC128_ANSWER_STRING))
#define VHS_FPGA_TYPE_STRING_SIZE	sizeof(XC2V3000_FPGA_ANSWER_STRING)

#define VHS_ANSWER_STRING_SIZE		VHS_ADC_TYPE_STRING_SIZE + VHS_FPGA_TYPE_STRING_SIZE

#endif
